### ISSUE TITLE
what about the origin SKSE plugins?

### ISSUE THREAD

**Issue by serephus** [CE0/OSA-SE#1]
Looks like the OSA.dll is redundant, but what about "CPConvert.dll" and "ConsolePlugin.dll" (Well, this Plugin isn't exactly necessary.)

BTW, index out of range in this function.
```
event OnStartModuleUI(string eventName, string dataString, float numArg, Form sender)
String[] data = StringUtil.split(dataString, ",")
Actor[] actro = PapyrusUtil.ActorArray(data.length - 1)

int i = 0
int l = data.length
    while i < l
actro[i] = game.getFormEx(data[i+1] as int) as actor
    i+=1
    endWhile

l = actro.length
i = 0
bool inScene = false
while i < l

if actro[i].GetFactionRank(OFaction[0]) != 1
else
inScene = true
i+10
endif
i+=1
endWhile
if inScene
else
    string[] newScene = osa.makeStage()
    osa.setActors(newScene, actro)
    osa.setModule(newScene, data[0])
    osa.start(newScene)
endif
endEvent
```

Here is a simple fix
```
event OnStartModuleUI(string eventName, string dataString, float numArg, Form sender)
    ;;PrintMessage("OSAEvent:Omni.OnStartModuleUI(string eventName=" + eventName + ", string dataString=" +\
    ;;                            dataString + ", float numArg=" + numArg + ", Form sender=" + sender + ")")
    String[] data = StringUtil.split(dataString, ",")
    Actor[] actro = PapyrusUtil.ActorArray(data.length - 1)

    int i = 0
    bool inScene = false
    bool bBreak = false

    while (i < data.length - 1) && !bBreak

        if game.getFormEx(data[i+1] as int) as actor
            actro[i] = game.getFormEx(data[i+1] as int) as actor
        else
            bBreak = True
        endif
        i += 1
    endWhile

    i = 0
    bBreak = False

    while i < actro.length && !bBreak
        if actro[i].GetFactionRank(OFaction[0]) == 1
            inScene = true
            bBreak = True
        endif
        i += 1
    endWhile
    if !inScene
        string[] newScene = osa.makeStage()
        osa.setActors(newScene, actro)
        osa.setModule(newScene, data[0])
        osa.start(newScene)
    endif
endEvent
```

**Comment by legendofceo** [comment]
thanks a lot for this dearfl,

CPConvert I'd like to get it working again but don't have the source, and scorpion_SK who wrote it isn't currently around to convert it to 64bit. I think it was a straight forward plugin so perhaps we can find someone else to write a new one. I left the commented areas in so I can remember the spots when the time comes. If it's packed in OSA it should be removed for now.

ConsoleUtil: I have to double check the code, it was used as a bandaid for auto-intimates to add equipment to NPCs without forcing them to full redress however I might have found a way around this. Have to double check the code and see if it's used anywhere and if so fix it / remove it. I don't think there is an updated ConsoleUtil yet for SE anyways.

I'll check into OSA.dll and upload the source I remember it only detected one small thing at boot up in the "major" actionscript class.

**Comment by serephus** [comment]
@CE0 
ConsoleUtil is actually a open source plugin, you can get the source code on nexusmod, so maybe u can get it converted to 64bit.  I'm currently learning how to make a skse plugin myself, but i don't think i can be any of help :(

**Comment by legendofceo** [comment]
Thanks Dearfl, 
We might not need consoleUtil at all but if we do that's a life saver. I have to dust off my setup and figure out how to export for x64 myself so most likely this weekend I will try to set that up and get a new OSA.dll and ConsoluteUtil dll up. Maybe I can help a little if you have any questions while learning to make a plugin, my C++ isn't very strong but not so bad either.

**Comment by serephus** [comment]
@CE0 
Well, I do have some question I can't figure out myself, for example, most of the plugins need to change skyrim's code, install a hook or something, so how can I locate these code's address? Is there any kind of way to do this efficiently.

**Comment by serephus** [comment]
@CE0 
I use IDA to look into skyrim's disassembly code, still I got no clue.
